Improve/mdc
entur/gbfs-loader-java pull request #179
Opened 2024-07-31 11:38 UTC by testower

Related to https://github.com/entur/lamassu/issues/250

This adds systemId to SubscriptionOptions, so it can be added to the mapped diagnostics context before each update. Example usage (in application):

```xml
            <appender name="console" class="ch.qos.logback.core.ConsoleAppender">
                <encoder class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
                    <providers>
                        <pattern>
                            <pattern>
                                {
                                    "serviceContext": {
                                        "service": "lamassu"
                                    },
                                    "mdc": {
                                        "systemId": "%X{systemId}"
                                    },
                                    "message": "%message\n%ex{full}",
                                    "severity": "%level",
                                    "reportLocation": {
                                        "filePath": "%logger",
                                        "lineNumber": "%line",
                                        "functionName": "%method"
                                    }
                                }
                            </pattern>
                        </pattern>
                    </providers>
                </encoder>
            </appender>
```

2024-07-31 12:18 UTC, testower commented
I wonder if there's some sort of best practice for adding stuff to MDC from libraries. Maybe namespacing?

2024-07-31 12:23 UTC, testower commented
These may also be relevant:

https://stackoverflow.com/questions/6073019/how-to-use-mdc-with-thread-pools
https://talktotheduck.dev/logging-best-practices-mdc-ingestion-and-scale#heading-plan-for-failure-eg-custom-thread-pool

2024-07-31 13:00 UTC, testower commented
One way to improve this is to add some lifecycle hooks or interceptors to the subscription, so that the application can make the MDC calls in stead of the library code.

2024-08-01 16:03 UTC, testower commented on src/main/java/org/entur/gbfs/SubscriptionUpdateInterceptor.java
> +public interface SubscriptionUpdateInterceptor {
document

2024-08-01 16:03 UTC, testower commented on src/main/java/org/entur/gbfs/GbfsSubscriptionManager.java
> +   * @param updateInterceptor
description

2024-08-01 16:03 UTC, testower commented on src/main/java/org/entur/gbfs/GbfsSubscriptionManager.java
> +   * @param updateInterceptor
description

2024-08-26 09:16 UTC, testower commented on src/main/java/org/entur/gbfs/loader/v2/GbfsV2Subscription.java
> +
Put this afterUpdate in a finally block for a try block around the update call (same for v3)

2024-09-04 10:33 UTC, hbruch requested changes
Calling the `updateInterceptor` in the `update` method does not support the intended use case to have a the system_id logged in case of exceptions, as exception logging occurs after `update()` was called and hence the externally set MDC is cleared already.

Possible solution could be to add `beforeUpdate`/`afterUpdate` as lifecycle methods to the GBFSSubscription classes and let them be called by the GBFSSubscriptionManager before/after calling update, e.g. like this
```java
public void update() {
    subscriptions
      .values()
      .parallelStream()
      .forEach(subscription ->
        Optional
          .ofNullable(customThreadPool)
          .orElse(ForkJoinPool.commonPool())
          .execute(() -> this.update(subscription))
      );
  }

  public void update(GbfsSubscription subscription) {
    try {
      subscription.beforeUpdate();
      subscription.update();
    } catch (RuntimeException e) {
      LOG.error("Error updating subscription", e);
    } finally {
      subscription.afterUpdate();
    }
  }
```

2024-09-09 12:09 UTC, merged